# nixpacks.toml - Railway build configuration

[phases.setup]
nixPkgs = ["...", "openssl", "pkg-config"]

[phases.build]
cmds = ["cargo build --release --features api --bin solana-vanity-api"]

[start]
cmd = "./target/release/solana-vanity-api"